// packages/react/src/badge.tsx
import {
  type CountFormat,
  type IconAsset,
  type IconResolver,
  createIconResolver,
  displayIcon,
  progressCount,
} from '@walangstudio/badgetrip-assets';
import type { AchievementView } from '@walangstudio/badgetrip-core';
import { type ReactNode, createContext, useContext, useMemo, useSyncExternalStore } from 'react';

const defaultResolver = createIconResolver();
const IconContext = createContext<IconResolver>(defaultResolver);

/** The icon resolver from the nearest `IconProvider`, or the built-in pack. */
export function useIconResolver(): IconResolver {
  return useContext(IconContext);
}

/** Supply a custom icon resolver (see `createIconResolver` in `@walangstudio/badgetrip-assets`). */
export function IconProvider({ icons, children }: { icons: IconResolver; children: ReactNode }) {
  return <IconContext.Provider value={icons}>{children}</IconContext.Provider>;
}

const MOTION = '(prefers-reduced-motion: reduce)';
const subscribeMotion = (cb: () => void) => {
  if (typeof window === 'undefined' || !window.matchMedia) return () => {};
  const mq = window.matchMedia(MOTION);
  mq.addEventListener('change', cb);
  return () => mq.removeEventListener('change', cb);
};
const reducedMotion = () =>
  typeof window !== 'undefined' && !!window.matchMedia && window.matchMedia(MOTION).matches;

/**
 * The icon to show for an achievement. Animated icons play only once unlocked and
 * fall back to their still frame under `prefers-reduced-motion`.
 */
export function useAchievementIcon(achievement: AchievementView): IconAsset {
  const icons = useContext(IconContext);
  const reduce = useSyncExternalStore(subscribeMotion, reducedMotion, () => false);
  const asset = useMemo(() => icons.resolve(achievement), [icons, achievement]);
  return displayIcon(asset, {
    unlocked: achievement.unlocked,
    reducedMotion: reduce,
  });
}

export type AchievementBadgeProps = {
  achievement: AchievementView;
  /** Icon edge in px. */
  size?: number;
  /** Show a progress bar while locked. Default true. */
  showProgress?: boolean;
  /** Show a "3/5" count under locked multi-step achievements. Default true. */
  showCount?: boolean;
  /** Wording of the count, e.g. `(p) => \`${p.current} of ${p.target}\``. */
  formatCount?: CountFormat;
  className?: string;
};

/**
 * A minimal, unstyled-by-class badge: icon, name, description, and progress while
 * locked. Locked icons render greyscale. Build your own with `useAchievementIcon`.
 */
export function AchievementBadge({
  achievement: a,
  size = 48,
  showProgress = true,
  showCount = true,
  formatCount,
  className,
}: AchievementBadgeProps) {
  const icon = useAchievementIcon(a);
  const count = showCount ? progressCount(a, formatCount) : null;
  return (
    <figure
      className={className}
      data-unlocked={a.unlocked}
      data-concealed={a.concealed}
      style={{
        margin: 0,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: 4,
        height: '100%',
      }}
    >
      <img
        src={icon.src}
        alt=""
        width={size}
        height={size}
        style={a.unlocked ? undefined : { filter: 'grayscale(1)', opacity: 0.45 }}
      />
      <figcaption style={{ textAlign: 'center', flex: 1 }}>
        <strong>{a.name}</strong>
        {a.description ? <div>{a.description}</div> : null}
      </figcaption>
      {showProgress && !a.unlocked && !a.concealed ? (
        <progress
          value={a.progress.percent}
          max={100}
          style={{ width: '100%' }}
          aria-label={`${a.name}: ${a.progress.percent}%`}
        />
      ) : null}
      {count === null ? null : (
        <small data-count style={{ fontSize: 12, opacity: 0.7 }}>
          {count}
        </small>
      )}
    </figure>
  );
}

// packages/angular/src/badge.ts
import { DOCUMENT, isPlatformBrowser } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  PLATFORM_ID,
  type Signal,
  computed,
  inject,
  input,
  signal,
} from '@angular/core';
import {
  type CountFormat,
  type IconAsset,
  displayIcon,
  progressCount,
} from '@walangstudio/badgetrip-assets';
import type { AchievementView } from '@walangstudio/badgetrip-core';
import { BADGETRIP_ICONS } from './service.js';

const MOTION = '(prefers-reduced-motion: reduce)';

function prefersReducedMotion(): Signal<boolean> {
  const win = inject(DOCUMENT).defaultView;
  if (!isPlatformBrowser(inject(PLATFORM_ID)) || !win?.matchMedia) return signal(false);
  const mq = win.matchMedia(MOTION);
  const reduce = signal(mq.matches);
  const onChange = () => reduce.set(mq.matches);
  mq.addEventListener('change', onChange);
  inject(DestroyRef).onDestroy(() => mq.removeEventListener('change', onChange));
  return reduce.asReadonly();
}

/**
 * The icon to show for an achievement. Animated icons play only once unlocked and
 * fall back to their still frame under `prefers-reduced-motion`. Call in an injection context.
 */
export function achievementIcon(achievement: Signal<AchievementView>): Signal<IconAsset> {
  const icons = inject(BADGETRIP_ICONS);
  const reduce = prefersReducedMotion();
  const asset = computed(() => icons.resolve(achievement()));
  return computed(() =>
    displayIcon(asset(), {
      unlocked: achievement().unlocked,
      reducedMotion: reduce(),
    }),
  );
}

/**
 * A minimal, unstyled-by-class badge: icon, name, description, and progress while
 * locked. Locked icons render greyscale. Build your own with `achievementIcon`.
 */
@Component({
  selector: 'badgetrip-achievement-badge',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [':host { display: block; height: 100%; }'],
  template: `
    <figure
      [attr.data-unlocked]="achievement().unlocked"
      [attr.data-concealed]="achievement().concealed"
      style="margin: 0; display: flex; flex-direction: column; align-items: center; gap: 4px; height: 100%"
    >
      <img
        [src]="icon().src"
        alt=""
        [width]="size()"
        [height]="size()"
        [style.filter]="achievement().unlocked ? null : 'grayscale(1)'"
        [style.opacity]="achievement().unlocked ? null : 0.45"
      />
      <figcaption style="text-align: center; flex: 1">
        <strong>{{ achievement().name }}</strong>
        @if (achievement().description) {
          <div>{{ achievement().description }}</div>
        }
      </figcaption>
      @if (showProgress() && !achievement().unlocked && !achievement().concealed) {
        <progress
          [value]="achievement().progress.percent"
          max="100"
          style="width: 100%"
          [attr.aria-label]="achievement().name + ': ' + achievement().progress.percent + '%'"
        ></progress>
      }
      @if (count(); as c) {
        <small data-count style="font-size: 12px; opacity: 0.7">{{ c }}</small>
      }
    </figure>
  `,
})
export class AchievementBadgeComponent {
  readonly achievement = input.required<AchievementView>();
  /** Icon edge in px. */
  readonly size = input(48);
  /** Show a progress bar while locked. */
  readonly showProgress = input(true);
  /** Show a "3/5" count under locked multi-step achievements. */
  readonly showCount = input(true);
  /** Wording of the count. */
  readonly formatCount = input<CountFormat | undefined>(undefined);
  protected readonly icon = achievementIcon(this.achievement);
  protected readonly count = computed(() =>
    this.showCount() ? progressCount(this.achievement(), this.formatCount()) : null,
  );
}
